module: CircuitBreaker
author: IBM
github_url: https://github.com/Kitura-Next/CircuitBreaker

theme: fullwidth
clean: true
exclude: [Packages]

readme: README.md

skip_undocumented: false
hide_documentation_coverage: false

xcodebuild_arguments: [-project, CircuitBreaker.xcodeproj, -target, CircuitBreaker, LIBRARY_SEARCH_PATHS=.build/debug]
